# Non Login Shell
set -g default-command "${SHELL}"

# improve colors
set -g default-terminal 'screen-256color'

bind-key % split-window -v -c "#{pane_current_path}"
bind-key ! split-window -h -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

unbind C-b
set -g prefix M-a

bind-key b break-pane -d

set -s set-clipboard off

# act like vim
setw -g mode-keys vi
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+
bind-key r source-file ~/.tmux.conf \; display-message "Sourced ~/.tmux.conf."

# Fine adjustment (1 or 2 cursor cells per bump)
bind -n S-Left resize-pane -L 2
bind -n S-Right resize-pane -R 2
bind -n S-Down resize-pane -D 1
bind -n S-Up resize-pane -U 1

# Coarse adjustment (5 or 10 cursor cells per bump)
bind -n M-Left resize-pane -L 10
bind -n M-Right resize-pane -R 10
bind -n M-Down resize-pane -D 5
bind -n M-Up resize-pane -U 5

# start window numbers at 1 to match keyboard order with tmux window order
set -g base-index 1
set-window-option -g pane-base-index 1

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# remove administrative debris (session name, hostname, time) in status bar
set -g status-left ''
set -g status-right " #{battery_status_bg} #{battery_percentage} | #(date '+%d/%m/%y - %H:%M') | - #{online_status} -"

# increase scrollback lines
set -g history-limit 99999

unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
#bind-key -t vi-copy 'v' begin-selection
#bind-key -t vi-copy 'y' copy-selection

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-battery'

set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'


bind-key h split-window -h 'htop'
bind-key t split-window -h -c ~/ 'vim ~/.todo/todo.txt'
bind-key C-l split-window -h 'tail -f log/development.log'

set -g mouse on

run-shell ~/tmux-better-mouse-mode/scroll_copy_mode.tmux
